/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Expertos.Experto;
import Expertos.ExpertoFactory;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author MARINA
 */
public class CambiarClave extends javax.swing.JFrame {

    /**
     * Creates new form CambiarClave
     */
    private Experto experto;
    private Usuario uEdit;
    private Login login;
    private String username;

    public CambiarClave(String username) {
        initComponents();
        this.setLocationRelativeTo(this);

        ExpertoFactory expertoFactory = new ExpertoFactory();
        experto = expertoFactory.getExperto("Usuario");
        this.username=username;
        uEdit = (Usuario) experto.find(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        psw_new_pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        psw_repeat_pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_cancel_pass = new javax.swing.JButton();
        btn_save_pass = new javax.swing.JButton();
        lbl_message_psw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambiar Clave"));

        jLabel6.setText("Nueva clave:");

        psw_new_pass.setText("jPasswordField2");

        jLabel7.setText("Confirmar:");

        psw_repeat_pass.setText("jPasswordField3");
        psw_repeat_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                psw_repeat_passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psw_repeat_passKeyTyped(evt);
            }
        });

        btn_cancel_pass.setText("Cancelar");
        btn_cancel_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel_passActionPerformed(evt);
            }
        });

        btn_save_pass.setText("Guardar");
        btn_save_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_passActionPerformed(evt);
            }
        });

        lbl_message_psw.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_message_psw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psw_repeat_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(psw_new_pass))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btn_save_pass)
                .addGap(49, 49, 49)
                .addComponent(btn_cancel_pass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(psw_new_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(psw_repeat_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_message_psw)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_pass)
                    .addComponent(btn_cancel_pass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psw_repeat_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psw_repeat_passKeyReleased

    }//GEN-LAST:event_psw_repeat_passKeyReleased

    private void psw_repeat_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psw_repeat_passKeyTyped

    }//GEN-LAST:event_psw_repeat_passKeyTyped

    private void btn_cancel_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel_passActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancel_passActionPerformed

    private void btn_save_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_passActionPerformed

        System.out.println("new pass: " + psw_new_pass.getText());
        System.out.println("repeat pass: " + psw_repeat_pass.getText());
        forgotPassword();

    }//GEN-LAST:event_btn_save_passActionPerformed

    private void saveData(Usuario u) {
        if (experto.persist(u, "edit") == 1) {
            JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
        }
    }

    public void forgotPassword() {

        if (psw_repeat_pass.getText().equals(psw_new_pass.getText())&& !psw_new_pass.getText().trim().equals("")) {
            uEdit.setContrasenia(psw_new_pass.getText());
            saveData(uEdit);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
       
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel_pass;
    private javax.swing.JButton btn_save_pass;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_message_psw;
    private javax.swing.JPasswordField psw_new_pass;
    private javax.swing.JPasswordField psw_repeat_pass;
    // End of variables declaration//GEN-END:variables
}
