/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import BDEstacionamientoV2.HibernateUtil;
import Expertos.Experto;
import Expertos.ExpertoFactory;
import Expertos.ExpertoPuesto;
import Modelo.Estacionamiento;
import Modelo.Tipovehiculo;
import Modelo.Puesto;
import Modelo.Turno;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.query.JRHibernateQueryExecuterFactory;
import net.sf.jasperreports.swing.JRViewer;
import org.hibernate.Session;
import utils.FunctionsTools;
import utils.UsuarioSingleton;

/**
 *
 * @author MARINA
 */
public class IngresoView extends javax.swing.JFrame {

    private Experto experto;
    private ExpertoFactory factory;

    List<Tipovehiculo> lista_tVehiulos;
    List<Puesto> lista_puestos;
    List<Object> ingresos;
    Puesto puesto_edit;

    /**
     * Creates new form Ingreso
     */
    public IngresoView() {

        lista_tVehiulos = new ArrayList<Tipovehiculo>();
        lista_puestos = new ArrayList<Puesto>();
        factory = new ExpertoFactory();

        initComponents();
        setLocationRelativeTo(null);

        loadComboPuestos();
        loadComboTipoVehi();

        experto = factory.getExperto("Estacionamiento");
        cargarTabla(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_menu_tabla = new javax.swing.JPopupMenu();
        item_registrar_salida = new javax.swing.JMenuItem();
        item_detalles = new javax.swing.JMenuItem();
        jd_detalles = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_deta_pantente = new javax.swing.JLabel();
        lbl_deta_tipo_vehiculo = new javax.swing.JLabel();
        lbl_deta_propietario = new javax.swing.JLabel();
        lbl_deta_puesto = new javax.swing.JLabel();
        lbl_deta_ingreso = new javax.swing.JLabel();
        lbl_deta_salida = new javax.swing.JLabel();
        lbl_deta_importe = new javax.swing.JLabel();
        lbl_deta_usuario = new javax.swing.JLabel();
        lbl_deta_nro_ticket = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_propietario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbx_tipovehiculos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbx_puestos = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        txt_patente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_ingresos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt_patente_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_search_ingreso = new javax.swing.JButton();
        chk_ver_todo = new javax.swing.JCheckBox();
        btn_Limpar = new javax.swing.JButton();

        item_registrar_salida.setText("Registrar Salida");
        item_registrar_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_registrar_salidaActionPerformed(evt);
            }
        });
        pop_menu_tabla.add(item_registrar_salida);

        item_detalles.setText("Ver detalles");
        item_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_detallesActionPerformed(evt);
            }
        });
        pop_menu_tabla.add(item_detalles);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel5.setText("Patente:");

        jLabel7.setText("Tipo vehiculo:");

        jLabel8.setText("Propietario:");

        jLabel9.setText("Puesto:");

        jLabel10.setText("Ingreso:");

        jLabel11.setText("Salida:");

        jLabel12.setText("Importe:");

        jLabel13.setText("Usuario:");

        jLabel14.setText("Nro Ticket:");

        lbl_deta_pantente.setText("jLabel15");

        lbl_deta_tipo_vehiculo.setText("jLabel16");

        lbl_deta_propietario.setText("jLabel17");

        lbl_deta_puesto.setText("jLabel18");

        lbl_deta_ingreso.setText("jLabel19");

        lbl_deta_salida.setText("jLabel20");

        lbl_deta_importe.setText("jLabel21");

        lbl_deta_usuario.setText("jLabel22");

        lbl_deta_nro_ticket.setText("jLabel23");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(lbl_deta_pantente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_deta_nro_ticket)
                            .addComponent(lbl_deta_usuario)
                            .addComponent(lbl_deta_importe)
                            .addComponent(lbl_deta_salida)
                            .addComponent(lbl_deta_ingreso)
                            .addComponent(lbl_deta_puesto)
                            .addComponent(lbl_deta_propietario)
                            .addComponent(lbl_deta_tipo_vehiculo))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_deta_pantente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_deta_tipo_vehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_deta_propietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_deta_puesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_deta_ingreso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_deta_salida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_deta_importe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_deta_usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbl_deta_nro_ticket))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_detallesLayout = new javax.swing.GroupLayout(jd_detalles.getContentPane());
        jd_detalles.getContentPane().setLayout(jd_detallesLayout);
        jd_detallesLayout.setHorizontalGroup(
            jd_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_detallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_detallesLayout.setVerticalGroup(
            jd_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_detallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Vehículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("  Patente/Identificador");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Propietario");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Vehiculo");

        cbx_tipovehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipovehiculosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Puesto");

        cbx_puestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cbx_puestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_puestosActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_tipovehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(cbx_tipovehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresos registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        tabla_ingresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patente", "Puesto", "Propietario", "Vehiculo", "Ingreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_ingresos.setComponentPopupMenu(pop_menu_tabla);
        tabla_ingresos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabla_ingresos);

        jLabel6.setText("Patente:");

        txt_patente_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_patente_searchActionPerformed(evt);
            }
        });

        jButton1.setText("Salida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_search_ingreso.setText("Buscar");
        btn_search_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_ingresoActionPerformed(evt);
            }
        });

        chk_ver_todo.setText("Ver Todo");
        chk_ver_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_ver_todoActionPerformed(evt);
            }
        });

        btn_Limpar.setText("Limpiar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_patente_search, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search_ingreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chk_ver_todo)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_patente_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_ingreso)
                    .addComponent(chk_ver_todo)
                    .addComponent(btn_Limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txt_patente.getText().equals("") || txt_propietario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Complete los campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);

        } else {

            Experto et = new ExpertoFactory().getExperto("Turno");
            List<Object> turnos_list = et.search(null);
            Timestamp fecha_ingreso = new Timestamp(Calendar.getInstance().getTimeInMillis());
            boolean open_service = false;

            Calendar c = Calendar.getInstance();
            Time hora = Time.valueOf(LocalTime.now());
            for (Object o : turnos_list) {
                Turno t = (Turno) o;
                if (t.getInicio().getTime() < hora.getTime()) {
                    open_service = true;
                    break;
                }
            }
            if (open_service) {
                try {
                    Estacionamiento e = new Estacionamiento();
                    e.setPatente(txt_patente.getText().toUpperCase());
                    e.setPropietario(txt_propietario.getText().toUpperCase());
                    e.setPuesto(lista_puestos.get(cbx_puestos.getSelectedIndex()));
                    e.setTipovehiculo(lista_tVehiulos.get(cbx_tipovehiculos.getSelectedIndex()));
                    e.setPersona(UsuarioSingleton.getInstance().getUsuario().getPersona());
                    e.setFechaIngreso(fecha_ingreso);

                    if (experto.persist(e, Experto.ADD) > 0) {
                        JOptionPane.showMessageDialog(this, "Ingreso registrado!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    }
                    loadComboPuestos();
                    cargarTabla(null);
                    clearForm();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el registro:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el registro:\nLa hora de ingreso no coincide con los turnos disponibles.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txt_patente_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_patente_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_patente_searchActionPerformed

    private void btn_search_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_ingresoActionPerformed
        if (!txt_patente_search.getText().trim().equals("")) {
            cargarTabla(txt_patente_search.getText().trim());
            txt_patente_search.setEnabled(false);
        }
    }//GEN-LAST:event_btn_search_ingresoActionPerformed

    private void item_registrar_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_registrar_salidaActionPerformed
        registrarSalida();
    }//GEN-LAST:event_item_registrar_salidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarSalida();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void item_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_detallesActionPerformed

        if (tabla_ingresos.getSelectedRow() > -1) {
            jd_detalles.setVisible(true);
            jd_detalles.setLocationRelativeTo(this);
            jd_detalles.setSize(420, 350);
            Estacionamiento e = (Estacionamiento) ingresos.get(tabla_ingresos.getSelectedRow());

            lbl_deta_importe.setText(e.getImporte() == null ? "" : "$ " + e.getImporte());
            lbl_deta_ingreso.setText(FunctionsTools.formatearFechaHora(e.getFechaIngreso().getTime()));
            lbl_deta_nro_ticket.setText(e.getNumeroTicket() != null ? "" + e.getNumeroTicket() : "");
            lbl_deta_pantente.setText(e.getPatente());
            lbl_deta_propietario.setText(e.getPropietario());
            lbl_deta_puesto.setText(e.getPuesto().getNumPuesto());
            lbl_deta_salida.setText(e.getFechaSalida() == null ? "" : FunctionsTools.formatearFechaHora(e.getFechaSalida().getTime()));
            lbl_deta_tipo_vehiculo.setText(e.getTipovehiculo().getTipoVehiculo());
            lbl_deta_usuario.setText(e.getPersona().getUsuario().getNombreUsuario());
        }
    }//GEN-LAST:event_item_detallesActionPerformed

    private void chk_ver_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_ver_todoActionPerformed
        cargarTabla(null);
    }//GEN-LAST:event_chk_ver_todoActionPerformed

    private void cbx_puestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_puestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_puestosActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed

        txt_patente_search.setEnabled(true);
        txt_patente_search.setText("");
        cargarTabla(null); // TODO add your handling code here:
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void cbx_tipovehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipovehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tipovehiculosActionPerformed

    private void registrarSalida() {
        if (tabla_ingresos.getSelectedRow() == -1 || ((Estacionamiento) ingresos.get(tabla_ingresos.getSelectedRow())).getFechaSalida() != null) {
            JOptionPane.showMessageDialog(this, "Seleccione un vehiculo", "ERROR!", JOptionPane.ERROR_MESSAGE);
            //return;
        } else {
            Estacionamiento e = (Estacionamiento) ingresos.get(tabla_ingresos.getSelectedRow());
            e.setPersona(UsuarioSingleton.getInstance().getUsuario().getPersona());

            Timestamp salida = new Timestamp(Calendar.getInstance().getTimeInMillis());
            e.setFechaSalida(salida);
            e.getPuesto().setEstadoPuesto(false);

            Experto ep = new ExpertoFactory().getExperto("Puesto");
            ep.persist(e.getPuesto(), Experto.EDIT);
            //imprimimos reporte
            double total = calcularTotal(e);
            e.setImporte(total);

            experto.persist(e, Experto.EDIT);
            printTicket(e, total);
            cargarTabla(null);
            loadComboPuestos();
        }
    }

    private double calcularTotal(Estacionamiento e) {
        double total = 0;
        double costo_turno = 0;
        Experto et = new ExpertoFactory().getExperto("Turno");
        List<Object> turnos_list = et.search(null);

        long horas = e.getFechaSalida().getTime() - e.getFechaIngreso().getTime();

        //14400000 son 4 horas en milisegundos
        int turnos = Math.round((float) horas / 14400000);
        if (turnos < 1) {
            turnos = 1;
        }
        //si llego de dia
        Time hora_entrada = Time.valueOf(FunctionsTools.formatearHora(e.getFechaIngreso().getTime()));
        Time hora_salida = Time.valueOf(FunctionsTools.formatearHora(e.getFechaSalida().getTime()));

        for (int i = 0; i < turnos_list.size(); i++) {
            Turno t = (Turno) turnos_list.get(i);
            //Turno t_next = null;
            //if (i < turnos_list.size() - 1) {
              //  t_next = (Turno) turnos_list.get(i + 1);
           // }
            if (t.getTipovehiculo().getIdTipoVehiculo() == e.getTipovehiculo().getIdTipoVehiculo()
                    && t.getInicio().getTime() <= hora_entrada.getTime()
                    && t.getFin().getTime() >= hora_salida.getTime()) {
                //entonces cobramos en torno a la tarifa del horario al que ingreso
                costo_turno = t.getPrecio();
                break;
            }
        }

        total = turnos * costo_turno;

        return total;
    }

    private void printTicket(Estacionamiento e, Double total) {

        try {
            Map map = new HashMap();
            JasperPrint print;
            JDialog reporte = new JDialog();
            reporte.setSize(850, 700);
            reporte.setModal(true);
            reporte.setTitle("Ticket");
            Session session = HibernateUtil.getSessionFactory().openSession();
            map.put(JRHibernateQueryExecuterFactory.PARAMETER_HIBERNATE_SESSION, session);
            map.put("ticketnro", e.getNumeroTicket().toString());
            map.put("patente", e.getPatente());
            map.put("propietario", e.getPropietario());
            map.put("tipovehiculo", e.getTipovehiculo().getTipoVehiculo());
            map.put("fecha_entrada", FunctionsTools.formatearFecha(e.getFechaIngreso().getTime()));
            map.put("fecha_salida", FunctionsTools.formatearFecha(e.getFechaSalida().getTime()));
            map.put("horaentrada", FunctionsTools.formatearHora(e.getFechaIngreso().getTime()));
            map.put("horasalida", FunctionsTools.formatearHora(e.getFechaSalida().getTime()));
            map.put("usuario", e.getPersona().getNombrePersona());
            map.put("total", "$" + String.format("%.2f", total));

//            URL reportTemplate = getClass().getClassLoader().getResource("reportes/ticket.jrxml");
//            JasperReport jasperReport = JasperCompileManager.compileReport(reportTemplate.getPath());
            print = JasperFillManager.fillReport(this.getClass().getClassLoader().getResourceAsStream("reportes/ticket.jasper"), map, new JREmptyDataSource());

            JRViewer jv = new JRViewer(print);
            reporte.getContentPane().add(jv);

            reporte.setVisible(true);

            reporte.addComponentListener(new java.awt.event.ComponentAdapter() {
                private void setAlwaysOnTop() {

                    setAlwaysOnTop();
                }
            });
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error: \n" + ex, "Error", JOptionPane.ERROR_MESSAGE);

            ex.printStackTrace();
        }
    }

    private void cargarTabla(String param) {

        Vector<String> tableHeaders = new Vector<String>();
        tableHeaders.add("Patente");
        tableHeaders.add("Puesto");
        tableHeaders.add("Propietario");
        tableHeaders.add("Vehiculo");
        tableHeaders.add("Ingreso");
        this.ingresos = experto.search(param, chk_ver_todo.isSelected() ? 1 : 0);
        tabla_ingresos.setModel(new DefaultTableModel(this.displayResult(this.ingresos), tableHeaders) {
            boolean[] canEdit = new boolean[]{false, false, false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    private Vector displayResult(List resultList) {
        Vector tableData = new Vector();

        for (Object o : resultList) {
            Estacionamiento e = (Estacionamiento) o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(e.getPatente());
            oneRow.add(e.getPuesto().getNumPuesto());
            oneRow.add(e.getPropietario());
            oneRow.add(e.getTipovehiculo().getTipoVehiculo());
            oneRow.add(FunctionsTools.formatearFechaHora(e.getFechaIngreso().getTime()));
            tableData.add(oneRow);
        }
        return tableData;
    }

    private void loadComboPuestos() {
        lista_puestos = new ArrayList<Puesto>();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List lista = ((ExpertoPuesto) factory.getExperto("Puesto")).puestosDisponibles();
        for (Object o : lista) {
            Puesto p = (Puesto) o;
            lista_puestos.add(p);
            model.addElement((p.getNumPuesto()));
        }
        this.cbx_puestos.setModel(model);
    }

    private void loadComboTipoVehi() {
        lista_tVehiulos = new ArrayList<Tipovehiculo>();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        List lista = factory.getExperto("TipoVehiculo").search(null);
        for (Object o : lista) {
            Tipovehiculo p = (Tipovehiculo) o;
            lista_tVehiulos.add(p);
            model.addElement((p.getTipoVehiculo()));
        }
        this.cbx_tipovehiculos.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_search_ingreso;
    private javax.swing.JComboBox<String> cbx_puestos;
    private javax.swing.JComboBox<String> cbx_tipovehiculos;
    private javax.swing.JCheckBox chk_ver_todo;
    private javax.swing.JMenuItem item_detalles;
    private javax.swing.JMenuItem item_registrar_salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_detalles;
    private javax.swing.JLabel lbl_deta_importe;
    private javax.swing.JLabel lbl_deta_ingreso;
    private javax.swing.JLabel lbl_deta_nro_ticket;
    private javax.swing.JLabel lbl_deta_pantente;
    private javax.swing.JLabel lbl_deta_propietario;
    private javax.swing.JLabel lbl_deta_puesto;
    private javax.swing.JLabel lbl_deta_salida;
    private javax.swing.JLabel lbl_deta_tipo_vehiculo;
    private javax.swing.JLabel lbl_deta_usuario;
    private javax.swing.JPopupMenu pop_menu_tabla;
    private javax.swing.JTable tabla_ingresos;
    private javax.swing.JTextField txt_patente;
    private javax.swing.JTextField txt_patente_search;
    private javax.swing.JTextField txt_propietario;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        txt_patente.setText("");
        txt_propietario.setText("");
        try {
            cbx_puestos.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No quedan mas puestos disponibles", "Error", JOptionPane.ERROR_MESSAGE);

        }

        cbx_tipovehiculos.setSelectedIndex(0);
    }
}
