/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Vista.cruds.PuestosABM;
import Vista.cruds.TarifaABM;
import utils.UsuarioSingleton;

/**
 *
 * @author MARINA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        permisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btn_personas = new javax.swing.JButton();
        btnTarifas = new javax.swing.JButton();
        btnPerfiles = new javax.swing.JButton();
        btnPuestos = new javax.swing.JButton();
        btnTipoVehiculo = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_settings = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Playa de Estacionamiento");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(669, 70));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(774, 115));

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnIngresar.setText("Ingresos");
        btnIngresar.setMaximumSize(new java.awt.Dimension(75, 31));
        btnIngresar.setMinimumSize(new java.awt.Dimension(75, 31));
        btnIngresar.setPreferredSize(new java.awt.Dimension(80, 31));
        btnIngresar.setRequestFocusEnabled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);

        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setDoubleBuffered(true);
        btnUsuarios.setPreferredSize(new java.awt.Dimension(80, 31));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios);

        btn_personas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_personas.setText("Personas");
        btn_personas.setPreferredSize(new java.awt.Dimension(80, 31));
        btn_personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_personas);

        btnTarifas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnTarifas.setText("Tarifas");
        btnTarifas.setPreferredSize(new java.awt.Dimension(80, 31));
        btnTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarifasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTarifas);

        btnPerfiles.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPerfiles.setText("Perfiles");
        btnPerfiles.setInheritsPopupMenu(true);
        btnPerfiles.setPreferredSize(new java.awt.Dimension(80, 31));
        btnPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfiles);

        btnPuestos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPuestos.setText("Puestos");
        btnPuestos.setPreferredSize(new java.awt.Dimension(80, 31));
        btnPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuestosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuestos);

        btnTipoVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnTipoVehiculo.setText("Tipo Vehiculo");
        btnTipoVehiculo.setPreferredSize(new java.awt.Dimension(105, 31));
        btnTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTipoVehiculo);

        btnReportes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setPreferredSize(new java.awt.Dimension(80, 31));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes);

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar \nSesion");
        btnCerrarSesion.setActionCommand("Cerrar Sesion");
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(110, 31));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        menu_settings.setText("Configuracion");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Perfiles");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_settings.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Puestos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_settings.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Tipo de Vehiculos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_settings.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Usuarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_settings.add(jMenuItem4);

        jMenuBar1.add(menu_settings);

        jMenu1.setText("Sistema");

        jMenuItem5.setText("Cambiar Clave");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        new IngresoView().setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btn_personasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personasActionPerformed

        new Vista.cruds.PersonasABM().setVisible(true);
    }//GEN-LAST:event_btn_personasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        new Reporte().setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        new Vista.cruds.UsuariosABM().setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarifasActionPerformed
        new Vista.cruds.TarifaABM().setVisible(true);
    }//GEN-LAST:event_btnTarifasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Vista.cruds.PerfilesABM().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Vista.cruds.PuestosABM().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new Vista.cruds.TipoVehiculoABM().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Vista.cruds.UsuariosABM().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilesActionPerformed
        new Vista.cruds.PerfilesABM().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilesActionPerformed

    private void btnPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuestosActionPerformed
        new Vista.cruds.PuestosABM().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuestosActionPerformed

    private void btnTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoVehiculoActionPerformed
        new Vista.cruds.TipoVehiculoABM().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnTipoVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPerfiles;
    private javax.swing.JButton btnPuestos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTarifas;
    private javax.swing.JButton btnTipoVehiculo;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btn_personas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu_settings;
    // End of variables declaration//GEN-END:variables

    private void permisos() {

        switch (UsuarioSingleton.getInstance().getUsuario().getPerfil().getNombrePerfil()) {
            case "admin":

                btnIngresar.setEnabled(true);
                btnReportes.setEnabled(true);
                btnTarifas.setEnabled(true);
                btnUsuarios.setEnabled(true);
                btn_personas.setEnabled(true);
                btnPuestos.setEnabled(true);
                btnTipoVehiculo.setEnabled(true);
                btnPerfiles.setEnabled(true);
                jMenuItem1.setEnabled(true);
                jMenuItem2.setEnabled(true);
                jMenuItem3.setEnabled(true);
                jMenuItem4.setEnabled(true);

                break;
            case "contador":
                btnIngresar.setEnabled(false);
                btnIngresar.setVisible(false);
                btnReportes.setEnabled(true);
                btnTarifas.setEnabled(false);
                btnTarifas.setVisible(false);
                btnUsuarios.setEnabled(false);
                btnUsuarios.setVisible(false);
                btn_personas.setVisible(false);
                btn_personas.setEnabled(false);
                btnPuestos.setEnabled(false);
                btnTipoVehiculo.setEnabled(false);
                btnPerfiles.setEnabled(false);
                btnPuestos.setVisible(false);
                btnTipoVehiculo.setVisible(false);
                btnPerfiles.setVisible(false);
                jMenuItem1.setVisible(false);
                jMenuItem1.setVisible(false);
                jMenuItem2.setEnabled(false);
                jMenuItem2.setVisible(false);
                jMenuItem3.setEnabled(false);
                jMenuItem3.setVisible(false);
                jMenuItem4.setEnabled(false);
                jMenuItem4.setVisible(false);
                break;
            case "operario":
                btnIngresar.setEnabled(true);
                btnReportes.setEnabled(true);
                btnPuestos.setEnabled(true);
                btnReportes.setVisible(false);
                btnTarifas.setEnabled(false);
                btnTarifas.setVisible(false);
                btnUsuarios.setEnabled(false);
                btnUsuarios.setVisible(false);
                btn_personas.setVisible(false);
                btn_personas.setEnabled(false);
                btnPuestos.setEnabled(false);
                btnTipoVehiculo.setEnabled(false);
                btnPerfiles.setEnabled(false);
                btnPuestos.setVisible(false);
                btnTipoVehiculo.setVisible(false);
                btnPerfiles.setVisible(false);
                jMenuItem1.setEnabled(false);
                jMenuItem2.setEnabled(false);
                jMenuItem3.setEnabled(false);
                jMenuItem4.setEnabled(false);
                break;
        }
        btnCerrarSesion.setEnabled(true);

    }
}
