package Modelo;
// Generated 16-mar-2019 23:47:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String nombrePersona;
     private double dniPersona;
     private String direccionPersona;
     private double telefonoPersona;
     private Set estacionamientos = new HashSet(0);
     private Usuario usuario;

    public Persona() {
    }

	
    public Persona(String nombrePersona, double dniPersona, String direccionPersona, double telefonoPersona) {
        this.nombrePersona = nombrePersona;
        this.dniPersona = dniPersona;
        this.direccionPersona = direccionPersona;
        this.telefonoPersona = telefonoPersona;
    }
    public Persona(String nombrePersona, double dniPersona, String direccionPersona, double telefonoPersona, Set estacionamientos, Usuario usuario) {
       this.nombrePersona = nombrePersona;
       this.dniPersona = dniPersona;
       this.direccionPersona = direccionPersona;
       this.telefonoPersona = telefonoPersona;
       this.estacionamientos = estacionamientos;
       this.usuario = usuario;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public double getDniPersona() {
        return this.dniPersona;
    }
    
    public void setDniPersona(double dniPersona) {
        this.dniPersona = dniPersona;
    }
    public String getDireccionPersona() {
        return this.direccionPersona;
    }
    
    public void setDireccionPersona(String direccionPersona) {
        this.direccionPersona = direccionPersona;
    }
    public double getTelefonoPersona() {
        return this.telefonoPersona;
    }
    
    public void setTelefonoPersona(double telefonoPersona) {
        this.telefonoPersona = telefonoPersona;
    }
    public Set getEstacionamientos() {
        return this.estacionamientos;
    }
    
    public void setEstacionamientos(Set estacionamientos) {
        this.estacionamientos = estacionamientos;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


