package Modelo;
// Generated 16-mar-2019 23:47:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private Integer idPuesto;
     private String numPuesto;
     private boolean estadoPuesto;
     private Set estacionamientos = new HashSet(0);

    public Puesto() {
    }

	
    public Puesto(String numPuesto, boolean estadoPuesto) {
        this.numPuesto = numPuesto;
        this.estadoPuesto = estadoPuesto;
    }
    public Puesto(String numPuesto, boolean estadoPuesto, Set estacionamientos) {
       this.numPuesto = numPuesto;
       this.estadoPuesto = estadoPuesto;
       this.estacionamientos = estacionamientos;
    }
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getNumPuesto() {
        return this.numPuesto;
    }
    
    public void setNumPuesto(String numPuesto) {
        this.numPuesto = numPuesto;
    }
    public boolean isEstadoPuesto() {
        return this.estadoPuesto;
    }
    
    public void setEstadoPuesto(boolean estadoPuesto) {
        this.estadoPuesto = estadoPuesto;
    }
    public Set getEstacionamientos() {
        return this.estacionamientos;
    }
    
    public void setEstacionamientos(Set estacionamientos) {
        this.estacionamientos = estacionamientos;
    }




}


