package Modelo;
// Generated 16-mar-2019 23:47:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Turno generated by hbm2java
 */
public class Tarifa  implements java.io.Serializable {


     private Integer idTarifa;
     private Tipovehiculo tipovehiculo;
     private String nombreTarifa;
     private double precioHora;
     private Date inicio;
     private Date fin;

    public Tarifa() {
    }

	
    public Tarifa(Tipovehiculo tipovehiculo, String nombreTurno, double precio) {
        this.tipovehiculo = tipovehiculo;
        this.nombreTarifa = nombreTurno;
        this.precioHora = precio;
    }
    public Tarifa(Tipovehiculo tipovehiculo, String nombreTurno, double precio, Date inicio, Date fin) {
       this.tipovehiculo = tipovehiculo;
       this.nombreTarifa = nombreTurno;
       this.precioHora = precio;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public Integer getIdTarifa() {
        return this.idTarifa;
    }
    
    public void setIdTarifa(Integer idTarifa) {
        this.idTarifa = idTarifa;
    }
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }
    public String getNombreTarifa() {
        return this.nombreTarifa;
    }
    
    public void setNombreTarifa(String nombreTarifa) {
        this.nombreTarifa = nombreTarifa;
    }
    public double getPrecioHora() {
        return this.precioHora;
    }
    
    public void setPrecioHora(double precioHora) {
        this.precioHora = precioHora;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


