package Modelo;
// Generated 16-mar-2019 23:47:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private Integer idTurno;
     private Tipovehiculo tipovehiculo;
     private String nombreTurno;
     private double precio;
     private Date inicio;
     private Date fin;

    public Turno() {
    }

	
    public Turno(Tipovehiculo tipovehiculo, String nombreTurno, double precio) {
        this.tipovehiculo = tipovehiculo;
        this.nombreTurno = nombreTurno;
        this.precio = precio;
    }
    public Turno(Tipovehiculo tipovehiculo, String nombreTurno, double precio, Date inicio, Date fin) {
       this.tipovehiculo = tipovehiculo;
       this.nombreTurno = nombreTurno;
       this.precio = precio;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public Integer getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(Integer idTurno) {
        this.idTurno = idTurno;
    }
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }
    public String getNombreTurno() {
        return this.nombreTurno;
    }
    
    public void setNombreTurno(String nombreTurno) {
        this.nombreTurno = nombreTurno;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }




}


