package Modelo;
// Generated 16-mar-2019 23:47:48 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idPersona;
     private Perfil perfil;
     private Persona persona;
     private String nombreUsuario;
     private String contrasenia;

    public Usuario() {
    }

    public Usuario(Perfil perfil, Persona persona, String nombreUsuario, String contrasenia) {
       this.perfil = perfil;
       this.persona = persona;
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }




}


